CREATE DATABASE PROYECTO;
USE PROYECTO;

CREATE TABLE DEPARTAMENTO(
   ID_DEP INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
   NOMBRE VARCHAR(25)
);

CREATE TABLE PROVINCIA(
   ID_PROV INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
   NOMBRE VARCHAR(25),
   ID_DEP INT,
   FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP)
);

CREATE TABLE PERSONA(
   ID_PER INT  AUTO_INCREMENT PRIMARY KEY NOT NULL,
   NOMBRE VARCHAR(25),
   APELLIDOS VARCHAR(50),
   FECHA_NAC DATE,
   EDAD INT(11),
   EMAIL VARCHAR(50),
   ID_DEP INT,
   ID_PROV INT,
   SEXO CHAR(1),
   FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP),
   FOREIGN KEY (ID_PROV) REFERENCES PROVINCIA(ID_PROV)
);

CREATE TABLE PROYECTO(
   ID_PROY INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
   NOMBREPROY VARCHAR(100),
   TIPOPROY VARCHAR(30)
);

CREATE TABLE DETALLE_PROYECTO(
   ID_DP INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL ,
   ID_PER INT,
   ID_PROY INT(11),
   FOREIGN KEY (ID_PER) REFERENCES PERSONA(ID_PER),
   FOREIGN KEY (ID_PROY) REFERENCES PROYECTO(ID_PROY)
);

INSERT INTO DETALLE_PROYECTO(ID_PER, ID_PROY) VALUES
(1, 1),
(2, 2),
(3, 2);

INSERT INTO PERSONA(NOMBRE, APELLIDOS, FECHA_NAC, EDAD, EMAIL, ID_DEP, ID_PROV, SEXO) VALUES
('CARLOS', 'FERNANDEZ', '2000-06-24', 22, 'CARLOS@GMAIL.COM', 1, 1, 'M'),
('ELENA', 'ROMERO ALARCON', '1997-09-1', 23, 'ROMAL@GMAIL.COM', 2, 3, 'F'),
('KARINA', 'PACAJES PAZ', '2000-10-10', 22, 'KARINA@GMAIL.COM', 3,6, 'F');

INSERT INTO PROVINCIA(NOMBRE, ID_DEP) VALUES
('PACAJES', 1),
('ITURRALDE', 1),
('CERCADO', 1),
('AZURDUY', 2),
('SACABA', 2),
('CEJA', 3);

INSERT INTO PROYECTO(NOMBREPROY, TIPOPROY) VALUES
('PROYECTO PLANTAS', 'AGRICULTURA'),
('PROYECTO SONRISAS', 'SALUD');

INSERT INTO DEPARTAMENTO (NOMBRE) VALUES
('LA PAZ'),
('COCHABAMBA'),
('EL ALTO');

CREATE FUNCTION FIBONACCI(LIM INT)
  RETURNS TEXT
  BEGIN
    DECLARE Y INT DEFAULT 0;
    DECLARE Z INT DEFAULT 1;
    DECLARE U INT DEFAULT 0;
    DECLARE X INT DEFAULT 1;
      DECLARE RESPONSE TEXT;
      IF LIM >= 1
         THEN
            SET RESPONSE = CONCAT(Y, ',');
      END IF;
      IF LIM >= 2
         THEN
            SET RESPONSE = CONCAT(RESPONSE, Z, ',');
      END IF;
      IF LIM >= 3
         THEN
            WHILE X <= (LIM - 2) DO
               SET U=Y+Z;
               SET RESPONSE = CONCAT(RESPONSE, U, ',');
               SET Y = Z;
               SET Z= U;
               SET X = X+1;
            END WHILE;
      END IF;
    RETURN RESPONSE;
  END;

CREATE FUNCTION SUMANUMEROS(CADENA VARCHAR(100))
RETURNS INT
BEGIN
    DECLARE NUM VARCHAR(50) DEFAULT '';
    DECLARE RES INTEGER DEFAULT 0;
    DECLARE FIBO VARCHAR(1);
    DECLARE C INTEGER DEFAULT 1;

    IF LENGTH(CADENA) > 0 THEN
        WHILE(C <= LENGTH(CADENA)) DO
            SET FIBO= SUBSTRING(CADENA, C, 1);
            IF FIBO = ',' THEN
                SET RES = RES + NUM;
               SET NUM = '';
            ELSE
                SET NUM = CONCAT(NUM, FIBO);
            END IF;
            SET C = C + 1;
        END WHILE;
        RETURN RES;
    ELSE
        RETURN 0;
    END IF;
END;

SELECT SUMANUMEROS(FIBONACCI(10));

CREATE VIEW VISTA AS
SELECT CONCAT(P.NOMBRE, ' ', P.APELLIDOS) AS CONTNOM, P.EDAD, P.FECHA_NAC, P3.NOMBREPROY
FROM PERSONA AS P
INNER JOIN DEPARTAMENTO D on P.ID_DEP = D.ID_DEP
INNER JOIN DETALLE_PROYECTO DP on P.ID_PER = DP.ID_PER
INNER JOIN PROVINCIA P2 on D.ID_DEP = P2.ID_DEP
INNER JOIN PROYECTO P3 on DP.ID_PROY = P3.ID_PROY
WHERE P.ID_DEP=3 AND P.FECHA_NAC='2000-10-10' AND P.SEXO='F';

SELECT *
FROM VISTA;


CREATE TRIGGER TRIGGER1
    BEFORE
        INSERT ON PROYECTO
    FOR EACH ROW
    BEGIN
        DECLARE NOMBRE VARCHAR(100);
        DECLARE TIPO VARCHAR(30);
        SET NOMBRE= NEW.NOMBREPROY;
        SET TIPO=NEW.TIPOPROY;
    end;

INSERT INTO PROYECTO(NOMBREPROY, TIPOPROY) VALUES('CORTE DE MADERAS', 'FORESTACION');
INSERT INTO PROYECTO(NOMBREPROY, TIPOPROY) VALUES('ANALFABETISMO', 'EDUCACION'),
                                                  ('NOCHE DE MUSEOS', 'CULTURA');
INSERT INTO PROYECTO(NOMBREPROY, TIPOPROY) VALUES('DONACION DE SANGRE', 'FORESTACION');

CREATE TRIGGER TRIGGER2
    BEFORE
        UPDATE ON PROYECTO
    FOR EACH ROW
    BEGIN
        DECLARE TIPO VARCHAR(30);
        SET TIPO=NEW.TIPOPROY;
    END;

UPDATE PROYECTO
SET TIPOPROY='SALUD'
WHERE TIPOPROY='FORESTACION';

ALTER TABLE PROYECTO ADD ESTADO VARCHAR(50);


CREATE TRIGGER TRIGGER3
    BEFORE
        INSERT ON PROYECTO
    FOR EACH ROW
    BEGIN
        DECLARE NOMBRE VARCHAR(100);
        DECLARE TIPO VARCHAR(30);
        SET NOMBRE= NEW.NOMBREPROY;
        SET TIPO=NEW.TIPOPROY;
        IF NEW.TIPOPROY='EDUCACION' OR NEW.TIPOPROY='FORESTACION' OR NEW.TIPOPROY='CULTURA'
        THEN
            SET NEW.ESTADO='ACTIVO';
            ELSE
            SET NEW.ESTADO='INACTIVO';
        end if;
    end;
INSERT INTO PROYECTO(NOMBREPROY, TIPOPROY) VALUES('SEMILLAS', 'FORESTACION');

CREATE  TRIGGER CALCULAEDAD BEFORE INSERT
   ON PERSONA
  FOR EACH ROW
  BEGIN
        DECLARE EDAD INTEGER DEFAULT 0;
        DECLARE EDAD2 INT DEFAULT 0;
        SET EDAD= (SELECT MAX(SUBSTR(NEW.FECHA_NAC, 1, 4))
            FROM PERSONA AS PER);
        SET EDAD2=(SELECT(SUBSTR(CURDATE(),1,4)));
        SET NEW.EDAD=EDAD2-EDAD;
  END;

INSERT INTO PERSONA(NOMBRE, APELLIDOS, FECHA_NAC, EMAIL, ID_DEP, ID_PROV, SEXO) VALUES('Anelis', 'Castillo', '2010-05-08', 'anelis@gmail.com', 3,6,'F');

CREATE TABLE PERSONA_COPIA(
   NOMBRE VARCHAR(25),
   APELLIDOS VARCHAR(50),
   FECHA_NAC DATE,
   EDAD INT(11),
   EMAIL VARCHAR(50),
   ID_DEP INT,
   ID_PROV INT,
   SEXO CHAR(1),
   FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP),
   FOREIGN KEY (ID_PROV) REFERENCES PROVINCIA(ID_PROV)
);

CREATE TRIGGER COPIA BEFORE INSERT
	ON PERSONA
  FOR EACH ROW
  BEGIN
		INSERT INTO PERSONA_COPIA(nombre, apellidos, fecha_nac, edad,email, id_dep, id_prov, sexo)
		VALUES(NEW.nombre, NEW.apellidos, NEW.fecha_nac, NEW.edad,NEW.email, NEW.id_dep, NEW.id_prov, NEW.sexo);
  END;

INSERT INTO PERSONA(NOMBRE, APELLIDOS, FECHA_NAC, EDAD, EMAIL, ID_DEP, ID_PROV, SEXO) VALUES ('FERNADO', 'CLAROS AGUILAR', '2005-04-18', 17,'CLAROSFERNADO@GMAIL.COM',1,2, 'M');

CREATE VIEW VISTA2 AS
SELECT PER.NOMBRE, PER.APELLIDOS, PER.EDAD, D.NOMBRE AS DEPARTAMENTO, P.NOMBRE AS PROVINCIA
FROM PERSONA AS PER
INNER JOIN DEPARTAMENTO D on PER.ID_DEP = D.ID_DEP
INNER JOIN DETALLE_PROYECTO DP on PER.ID_PER = DP.ID_PER
INNER JOIN PERSONA_COPIA PC on D.ID_DEP = PC.ID_DEP
INNER JOIN PROVINCIA P on D.ID_DEP = P.ID_DEP
INNER JOIN PROYECTO P2 on DP.ID_PROY = P2.ID_PROY
WHERE PER.EDAD>=18 AND D.ID_DEP=1;
